server:
  port: 9527

spring:
  application:
    name: memories-zuul-gateway

zuul:
  prefix: /itzzh
  ignored-services: "*"
  routes:
    mymemory.serviceId: memories-memory
    mymemory.path: /mymemory/**

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: itzzh-memories
  company.name: www.itzzh.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
